# Used by "mix format"

# `mix spark.formatter --extensions Expresso.Extension,Expresso.Presenter.Extension`
# manages this list. Run it after a change to an entity or an option of a DSL. The formatter then adds no
# parentheses to a call of the DSL. It removes none either, so write a call
# without them.
spark_locals_without_parens = [
  alt: 1,
  any: 1,
  aspect: 1,
  at: 1,
  attribute: 2,
  attribute: 3,
  audio: 1,
  audio: 2,
  auto_reveal: 1,
  by: 1,
  class: 1,
  code: 0,
  code: 1,
  code: 2,
  column: 0,
  column: 1,
  columns: 0,
  columns: 1,
  controls: 1,
  css: 1,
  diagram: 1,
  diagram: 2,
  dim: 1,
  duration: 1,
  each: 1,
  easing: 1,
  effect: 1,
  element: 1,
  embed: 1,
  embed: 2,
  event: 3,
  event: 4,
  fallback: 1,
  flag: 1,
  footnote: 1,
  footnote: 2,
  goto: 1,
  group: 1,
  handout: 1,
  header: 1,
  heading: 1,
  highlight: 1,
  image: 1,
  image: 2,
  interactive: 1,
  item: 1,
  item: 2,
  key: 3,
  key: 4,
  label: 1,
  labels: 1,
  lang: 1,
  level: 1,
  line_numbers: 1,
  lines: 1,
  list: 0,
  list: 1,
  loop: 1,
  mark: 4,
  mark: 5,
  match: 1,
  math: 1,
  math: 2,
  meta: 1,
  mode: 1,
  mode: 2,
  move_to: 1,
  name: 1,
  notes: 1,
  on: 1,
  on: 2,
  ordered: 1,
  other: 1,
  part: 1,
  part: 2,
  pause: 0,
  pause: 1,
  poster: 1,
  print_notes: 1,
  progress: 1,
  property: 2,
  property: 3,
  qr_code: 1,
  qr_code: 2,
  quotation: 1,
  quotation: 2,
  reset: 1,
  reveal: 1,
  root: 1,
  row: 1,
  row: 2,
  scroll: 1,
  set: 1,
  size: 1,
  slide: 0,
  slide: 1,
  slide: 2,
  slide_numbers: 1,
  slide_template: 1,
  spacer: 0,
  spacer: 1,
  speed: 1,
  src: 1,
  state: 1,
  steps: 1,
  sync: 1,
  table: 0,
  table: 1,
  template: 1,
  text: 1,
  text_area: 0,
  text_area: 1,
  text_box: 0,
  text_box: 1,
  theme: 1,
  title: 1,
  transition: 1,
  video: 1,
  video: 2,
  whole_first: 1,
  width: 1
]

[
  import_deps: [:spark, :stream_data, :temple],
  inputs: ["{mix,.formatter,.check}.exs", "{config,lib,tools,test,examples}/**/*.{ex,exs}"],
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: spark_locals_without_parens]
]
